k-ardliyan/01/App.jsx
- add header
- add content dengan arr.map
- add footer
=> feat: add tambah latihan 01

k-ardliyan/02/App.jsx
- latihan form
- handle error
- tampilkan submit form
- bonus delete 😅
=> feat: add latihan form 30 Mei 2024

michael/latihan-react-3/App.css, michael/latihan-react-3/App.js
=> latihan-react-3

Danis Ardani/01/CounterApp.jsx, Danis Ardani/02/NoteApp.jsx
=> feat: add counter app and note app

k-ardliyan/03/App.jsx
- CRUD Daftar Belanja
- Menggunakan Class
=> feat: latihan crud 03 Juni 2024

michael/latihan-react-4/App.css, michael/latihan-react-4/App.js
Ini latihan react CRUD hari senin kak. Kemarin saya tidak sempat menyelesaikannya.
Michael
=> latihan react crud

k-ardliyan/04/App.css, k-ardliyan/04/App.jsx
- Menggunakan function component
- Tambah components for Counter and FormSubmit
-  Tambah CSS styles
=> chore: latihan 04 tgl 04/06/2024

michael/latihan-react-5/App.css, michael/latihan-react-5/App.js
mengubah dari class component ke functional component dan menambahkan counter app
Michael
=> mengubah dari class component ke functional component dan menambahkan counter app

k-ardliyan/readme.md, k-ardliyan/todo-class/App.css, k-ardliyan/todo-class/App.jsx, k-ardliyan/todo-class/TodoContext.jsx, k-ardliyan/todo-class/components/TodoForm.jsx, k-ardliyan/todo-class/components/TodoItem.jsx, k-ardliyan/todo-class/components/TodoList.jsx, k-ardliyan/todo-function/App.css, k-ardliyan/todo-function/App.jsx, k-ardliyan/todo-function/TodoContext.jsx, k-ardliyan/todo-function/components/TodoForm.jsx, k-ardliyan/todo-function/components/TodoItem.jsx, k-ardliyan/todo-function/components/TodoList.jsx
- todo menggunakan class component
- todo menggunakan function component
- project deploy => [Todo App React](https://todo-react.k-ardliyan.my.id)
=> feat: add project todo (1) & (2)

michael/latihan-react-6/App.css, michael/latihan-react-6/App.js
ini sistem searchnya tiap mengetikkan huruf di filternya kak
michael
=> menambahakan search app

k-ardliyan/05/App.css, k-ardliyan/05/App.jsx, k-ardliyan/05/components/Counter.jsx, k-ardliyan/05/components/FormSubmit.jsx, k-ardliyan/05/components/ShoppingList.jsx
- Menambahkan fitur search barang pada daftar belanja
=> chore: latihan 05/06/2024

k-ardliyan/expo-01/index.tsx, k-ardliyan/expo-01/style.tsx
- Add calculator app with basic functionality
=> chore: latihan expo-01 11 Juni 2024

michael/latihan-react-native-1/App.tsx, michael/latihan-react-native-1/style.tsx
Tugas hari selasa, 11 Juni 2024 calculator app
Michael
=> latihan react native calculator app

Nirwana/.gitignore, Nirwana/src/App.js, Nirwana/src/index.css, Nirwana/src/index.js
Terima kasih sebelumnya, Kak ^^
=> tugas counter 28 mei

wahuy/ProjectNoteAppExpo/index.tsx
=> Mengumpulkan Project NoteApp

Wiji/TODO APP NOTE EXPO/index.tsx, Wiji/TODO APP NOTE EXPO/style.tsx
maaf kak agak telat karena kemarin baru check up di rs
=> menambah wiji

rickydwik/tugas_noteapp/App.tsx, rickydwik/tugas_noteapp/Index.tsx
=> tugas noteapp

Agus/Latihan Expo 01/index.tsx, Agus/Project-Individu-Note-App/index.tsx
=> note Push: 18-06 08:30

Yusuf/TUGAS WEATHER APP MUHAMMAD YUSUF/app/(tabs)/_layout.tsx, Yusuf/TUGAS WEATHER APP MUHAMMAD YUSUF/app/(tabs)/explore.tsx, Yusuf/TUGAS WEATHER APP MUHAMMAD YUSUF/app/(tabs)/index.tsx, Yusuf/TUGAS WEATHER APP MUHAMMAD YUSUF/app/(tabs)/src/components/customTextInput.js, Yusuf/TUGAS WEATHER APP MUHAMMAD YUSUF/app/(tabs)/src/components/weatherInfo.js, Yusuf/TUGAS WEATHER APP MUHAMMAD YUSUF/app/(tabs)/src/components/weatherSearch.js, Yusuf/TUGAS WEATHER APP MUHAMMAD YUSUF/app/(tabs)/src/constant.js, Yusuf/TUGAS WEATHER APP MUHAMMAD YUSUF/app/+html.tsx, Yusuf/TUGAS WEATHER APP MUHAMMAD YUSUF/app/+not-found.tsx, Yusuf/TUGAS WEATHER APP MUHAMMAD YUSUF/app/_layout.tsx
=> Tugas weather app yusuf

michael/tugas weather-app/App.js, michael/tugas weather-app/constant.js, michael/tugas weather-app/package.json, michael/tugas weather-app/readme.md
Pada Snack Expo, kodenya error kak, ada dependency yang harus diinstal pakai "npm install" tapi pada snack tidak bisa diakses terminalnya. Sehingga saya kumpulkan lewat github.
Michael
Screenshot aplikasi
1. Main menu
2. History
=> Tugas Weather App
